// import bcrypt from "bcryptjs";

export const data = [
	{
		id: 1,
		name: "Winter body",
		size: [37, 38, 39, 40, 41],
		company: "Nike",
		description: [
			{ support: "گارانتی مادام العمر" },
			{ support: "ارسال رایگان" },
			{ support: "اورجینال" },
		],
		price: 120,
		offPrice: 120,
		discount: 0,
		image: "https://s4.uupload.ir/files/item1_soj.jpg",
	},
	{
		id: 2,
		name: "K 195",
		size: [35, 36, 37, 38],
		company: "Nike",
		description: [{ support: "گارانتی مادام العمر" }, { support: "اورجینال" }],
		price: 110,
		// offPrice: 100,
		discount: 8,
		image: "https://s4.uupload.ir/files/item2_fc5s.jpg",
	},
	{
		id: 3,
		name: "Vans",
		size: [40, 41, 42, 43],
		company: "Mely",
		description: [
			{ support: "گارانتی مادام العمر" },
			{ support: "اورجینال" },
			{ support: "ارسال رایگان" },
		],
		price: 99,
		offPrice: 89,
		discount: 10,
		image: "https://s4.uupload.ir/files/item3_zvc9.jpg",
	},
	{
		id:4,
		name: "White",
		size: [35, 36, 37, 38],
		company: "Nike",
		description: [
			{ support: "گارانتی مادام العمر" },
			{ support: "اورجینال" },
			{ support: "ارسال رایگان" },
		],
		price: 260,
		offPrice: 220,
		discount: 15,
		image: "https://s4.uupload.ir/files/item4_zr94.jpg",
	},
	{
		id: 7,
		name: "Croopped-shoe",
		size: [46,47,48],
		company: "Adidas",
		description: [
			{ support: "گارانتی مادام العمر" },
			{ support: "اورجینال" },
			{ support: "ارسال رایگان" },
		],
		price: 150,
		offPrice: 150,
		discount: 0,
		image: "https://s4.uupload.ir/files/item5_24ye.jpg",
	},
	{
		id: 8,
		name: "Blues",
		size: [32,33,34,35,36,37],
		company: "Adidas",
		description: [
			{ support: "گارانتی مادام العمر" },
			{ support: "اورجینال" },
			{ support: "ارسال رایگان" },
		],
		price: 220,
		offPrice: 200,
		discount: 13,
		image: "https://s4.uupload.ir/files/item6_7jfy.jpg",
	},
];

// export const users = [
// 	{
// 		name: "Saheb mohamadi",
// 		email: "saheb.ex@gmail.com",
// 		password: bcrypt.hashSync("12345", 8),
// 		phoneNumber: "09180000000",
// 		isAdmin: true,
// 	},
// 	{
// 		name: "John",
// 		email: "user@example.com",
// 		password: bcrypt.hashSync("1234", 8),
// 		isAdmin: false,
// 		phoneNumber: "09181230000",
// 	},
// ];
